// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoAppMVC.Models;

namespace TodoAppMVC.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210901062953_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TodoAppMVC.Models.Todo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Ders Çalış",
                            UserID = 1
                        },
                        new
                        {
                            ID = 3,
                            Description = "Projeyi tamamla",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("TodoAppMVC.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Ad = "Onur Kağan",
                            Password = "123",
                            Username = "onurkagan"
                        },
                        new
                        {
                            ID = 2,
                            Ad = "Administrator",
                            Password = "123",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("TodoAppMVC.Models.Todo", b =>
                {
                    b.HasOne("TodoAppMVC.Models.User", "User")
                        .WithMany("TodoListByUser")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoAppMVC.Models.User", b =>
                {
                    b.Navigation("TodoListByUser");
                });
#pragma warning restore 612, 618
        }
    }
}
